In [13]:
%pip install numpy
%pip install time


[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip



Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time

[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import numpy as np
import time

In [15]:
start = time.time()
n = 1000000
x = np.arange(n) **2
end = time.time()
ending = end - start
print(x,ending)

[         0          1          4 ... -733379959 -731379964 -729379967] 0.004004716873168945


In [16]:
# a =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,10]]])
# a

a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

a[:,0]

array([ 1,  4,  7, 10])

In [17]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

a[0,:]

array([1, 2, 3])

In [21]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

a[1:2,1:2]

array([[4, 5, 6]])

In [22]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a[3,:]

array([10, 11, 12])

In [26]:
np.zeros([5,9])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
a = np.zeros([9,12],dtype="int")
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])